name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and test
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy to Elastic Beanstalk
      run: |
        sudo apt-get install -y zip
        cd ./publish
        zip -r application.zip .
        aws s3 cp application.zip s3://elasticbeanstalk-eu-central-1-084374805449
        aws elasticbeanstalk create-application-version --application-name btc-playground-api --version-label v-${{ github.run_number }} --source-bundle S3Bucket="elasticbeanstalk-eu-central-1-084374805449",S3Key="application.zip"
        aws elasticbeanstalk update-environment --environment-name btc-playground-api-dev --version-label v-${{ github.run_number }}
