name: Publish API

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build API
        run: dotnet build

      - name: Run Tests
        run: dotnet test

      - name: Upload Binaries via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: btcis.me
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /api
          local-dir: ./bin/Release/net6.0/publish
